version: '3'

services:
    app:
      build: docker/php/8.1     
      container_name: php
      tty: true
      ports:
        - 80:80
      volumes:
        - ./app:/var/www/html/
      hostname: localhost
